export { default as RegisterPage } from './registerPage/RegisterPage';
export { default as HomePage } from './homePage/HomePage';
export { default as InvoicePage } from './invoicePage/InvoicePage';
export { default as DetailedInvoicePage } from './detailedInvoicePage/DetailedInvoicePage';
export { default as DetailedSoaPage } from './detailedSoaPage/DetailedSoaPage';
export { default as SoaPage } from './soaPage/SoaPage';
export { default as UploadPage } from './uploadPage/UploadPage';
//export { default as CompareDocumentPage } from './compareDocumentPage/CompareDocumentPage';
export { default as Signinpage } from './signInPage/Signinpage';
export { default as ProductPage } from './productPage/ProductPage';
export {default as ResetPage} from './ResetPage/ResetPage';
export { default as EditDocumentPage } from './editDocumentPage/EditDocumentPage';
export { default as EditDocumentPageInvoice } from './editDocumentPage/EditDocumentPageInvoice';
export { default as EditDocumentPageSOA } from './editDocumentPage/EditDocumentPageSOA';
export{ default as ForgotPassword } from './forgotpasswordpage/forgotpasswordpage';